theme: jekyll-theme-cayman
title: "Think Twice<br>Code Once"
description: "Robert Sabirov - Hydra13 - Software Engineer"
github:
  notes_url: https://github.com/hydra13/Hydra13-Notes
  python_examples_url: https://github.com/hydra13/PythonExamples